Repository bold-commerce/m1-bold-checkout-payment-booster, pull requests merged in 2024-11, with the labels that each got.

#56 CHK-4478: Implement Express Pay Functionality
  Block/Checkout/Expresspay.php
  Model/Config.php
  Service/ExpressPay/QuoteConverter.php
  controllers/ExpresspayController.php
  controllers/IndexController.php
  design/frontend/base/default/layout/bold/checkout.xml
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  etc/config.xml
  etc/system.xml
  modman
  skin/frontend/base/default/css/bold/checkout_payment_booster/expresspay.css
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: enhancement

#57 CHK-6322: Fix Incompatibility Between Express Pay and Fastlane
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  design/frontend/base/default/template/bold/checkout_payment_booster/payment/form/base.phtml
  design/frontend/base/default/template/bold/checkout_payment_booster/payment/form/bold_method.phtml
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: bug

#60 CHK-6399: Implement Google Pay in Express Pay
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: enhancement

#59 CHK-5482: Update CODEOWNERS
  .github/CODEOWNERS
Labels: developer-experience

#61 CHK-4601: Render Express Pay Buttons on Cart Page
  Block/Checkout/Expresspay.php
  Model/Config.php
  Observer/CartObserver.php
  design/frontend/base/default/layout/bold/checkout.xml
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  etc/config.xml
  etc/system.xml
Labels: enhancement

#62 CHK-4599: Implement Express Pay in Mini Cart
  Block/Checkout/Expresspay.php
  Model/Config.php
  Observer/CartObserver.php
  Observer/CheckoutObserver.php
  Observer/PredispatchObserver.php
  design/frontend/base/default/layout/bold/checkout.xml
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  etc/config.xml
  etc/system.xml
  skin/frontend/base/default/css/bold/checkout_payment_booster/expresspay.css
Labels: enhancement

#63 CHK-6578 Autodetect local development urls
  Service/BoldClient.php
  Service/ShopInfo.php
Labels: developer-experience
