Repository bold-commerce/m1-bold-checkout-payment-booster, pull requests merged in 2024-12, with the labels that each got.

#64 CHK-6471 update checkout order after shipping method change
  Observer/CheckoutObserver.php
  etc/config.xml
Labels: bug

#66 CHK-6805 Bump version number 2.0.1
  etc/config.xml
Labels: release

#68 Revert "CHK-6805 Bump version number 2.0.1"
  etc/config.xml
Labels: release

#71 CHK-6850 Remove hydrate order calls
  controllers/IndexController.php
  design/frontend/base/default/template/bold/checkout_payment_booster/payment/form/base.phtml
Labels: bug

#72 CHK-6836: Provide Page Source as Option to EPS Payments SDK
  Block/Checkout/Expresspay.php
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: enhancement

#73 CHK-6893: Fix Error Thrown by Express Pay When Shipping Address Country Has No Region
  Service/ExpressPay/QuoteConverter.php
Labels: bug

#75 CHK-6954: Remove Requirement on Region Name, Region Identifier and Postal Code During Sidekick Order Hydration
  Service/Order/Hydrate/ExtractData.php
Labels: bug

#77 CHK-6925: Fix Shipping Error Thrown During Initialization of PayPal in Express Pay on Cart Page
  Observer/BeforeCheckoutSaveShippingObserver.php
  etc/config.xml
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: bug
