Repository bold-commerce/m1-bold-checkout-payment-booster, pull requests merged in 2025-01, with the labels that each got.

#78 CHK-6926: Fix PayPal Buttons Rendered on Top of Product Images on Product Detail Page
  skin/frontend/base/default/css/bold/checkout_payment_booster/expresspay.css
Labels: bug

#79 CHK-7005: Prevent Conversion of Erroneous Shipping Options While Converting Express Pay Order API Data
  Service/ExpressPay/QuoteConverter.php
Labels: bug

#80 CHK-6711: Use Separate Bold Checkout Flow ID for Digital Wallet Orders on Product Detail Page
  Observer/ConfigObserver.php
  Observer/PredispatchObserver.php
  Service/Bold.php
  Service/Flow.php
  Service/Order/Init.php
Labels: enhancement

#81 CHK-6989: Render Multiple Sets of Digital Wallet Payment Buttons on the Same Page
  Block/Checkout/Expresspay.php
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: bug

#84 CHK-7007: Rebrand Configuration Settings to Reflect New Product Name
  etc/system.xml
Labels: marketing

#82 CHK-7191: Hide Digital Wallets Title in Mini Cart on Checkout Page
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  skin/frontend/base/default/css/bold/checkout_payment_booster/expresspay.css
Labels: bug

#83 CHK-6712: Use Separate Bold Checkout Flow ID for Digital Wallet Orders on Cart Page
  Observer/ConfigObserver.php
  Observer/PredispatchObserver.php
  Service/Flow.php
Labels: enhancement

#70 CHK-4315: Implement Express Pay in Cart, Mini Cart & on Product Detail Page
  Block/Checkout/Expresspay.php
  Model/Config.php
  Observer/AddProductCompleteObserver.php
  Observer/BeforeAddToCartObserver.php
  Observer/BeforeCheckoutSaveShippingObserver.php
  Observer/CheckoutObserver.php
  Observer/ConfigObserver.php
  Observer/PredispatchObserver.php
  Service/Bold.php
  Service/ExpressPay/QuoteConverter.php
  Service/Flow.php
  Service/Order/Hydrate/ExtractData.php
  Service/Order/Init.php
  controllers/ExpresspayController.php
  controllers/IndexController.php
  design/frontend/base/default/layout/bold/checkout.xml
  design/frontend/base/default/template/bold/checkout_payment_booster/checkout/expresspay.phtml
  etc/config.xml
  etc/system.xml
  skin/frontend/base/default/css/bold/checkout_payment_booster/expresspay.css
  skin/frontend/base/default/js/bold/checkout_payment_booster/expresspay.js
Labels: enhancement

#69 CHK-6805: Release Version 2.1.0
  etc/config.xml
Labels: release

#86 CHK-7258: Release Version 2.1.1
  etc/config.xml
Labels: release
